- set_fact:
    burpsuite_edition: pro
    burpsuite_channel: Stable
    burpsuite_folder: /opt/burpsuite

- name: Create Burp Suite directory
  ansible.builtin.file:
    path: "{{ burpsuite_folder }}"
    state: directory
  
- name: Burp | Dependencies | Install | Pip3
  ansible.builtin.pip:
    name: jmespath

- name: Burp Suite | Lookup Latest Version | Retrieve PortSwigger Releases API Data
  ansible.builtin.set_fact:
    burp_release_data: "{{ lookup('url', 'https://portswigger.net/burp/releases/data?lastId=-1&pageSize=20') }}"

- name: Burp Suite | Lookup Latest Version | Get Latest Release
  ansible.builtin.set_fact:
    burp_latest_release: "{{ burp_release_data | community.general.json_query(latest_release_query) }}"
  vars:
    latest_release_query: >-
      ResultSet.Results[?contains(@.releaseChannels, '{{ burpsuite_channel }}')].builds[]
      | [?ProductId == '{{ burpsuite_edition }}' && ProductPlatform == 'Linux']
      | [0]

- name: Burp Suite | Lookup Latest Version | Set Release Facts
  ansible.builtin.set_fact:
    _burpsuite_installer_version: "{{ burp_latest_release | community.general.json_query('@.Version') }}"
    burpsuite_installer_sha256_checksum: "{{ burp_latest_release | community.general.json_query('@.Sha256Checksum') }}"

- name: Burp Suite | Lookup Latest Version | Latest Version
  ansible.builtin.debug:
    msg: "Latest version for Burp Suite {{ burpsuite_edition | capitalize }} ({{ burpsuite_channel }}) is {{ _burpsuite_installer_version }}"

- name: Burp Suite | Install | Set Installer Filename
  ansible.builtin.set_fact:
    burpsuite_installer_script: "burpsuite_{{ burpsuite_edition }}_linux_v{{ _burpsuite_installer_version | regex_replace('\\.', '_') }}.jar"

- name: Burp Suite | Install | Download Installer
  ansible.builtin.get_url:
    url: "https://portswigger.net/burp/releases/download?product={{ burpsuite_edition }}&type=linux&version={{ _burpsuite_installer_version }}"
    dest: "{{ burpsuite_folder }}/{{ burpsuite_installer_script}}"
    mode: 0644

- name: Burp Suite | Extras | Download jar Files
  ansible.builtin.get_url:
    url: "{{ item.value.url }}"
    dest: "{{ burpsuite_folder }}/{{ item.value.jar }}"
    checksum: "{{ item.value.checksum }}"
    mode: 0644
  loop: "{{ lookup('dict', burpsuite_extras_jars) }}"

- name: Ysoserial | Debian | Install | Download
  ansible.builtin.get_url:
    url: "{{ ysoserial_dl_url }}"
    dest: "{{ burpsuite_folder }}/ysoserial.jar"
    mode: 0644