---
  - name: 'evil-winrm path completion'
    block:
      - name: 'Check ruby version'
        shell: "ruby --version | awk '{print $2}' | sed 's/p.*$//'"
        register: ruby_version
        
      - name: 'Install dependencies'
        package:
          name: libreadline-dev
          state: present
        become: true

      - name: 'Create temp dir'
        tempfile:
          state: directory
        register: tempdir

      - name: 'Download ruby'
        get_url:
          url: 'https://ftp.ruby-lang.org/pub/ruby/{{ ruby_version.stdout | regex_search("^[0-9]+\.[0-9]+") }}/ruby-{{ ruby_version.stdout }}.tar.gz'
          dest: '{{ tempdir.path }}/'

      - name: 'Extract files'
        unarchive:
          src: '{{ tempdir.path }}/ruby-{{ ruby_version.stdout }}.tar.gz'
          dest: '{{ tempdir.path }}/'
          remote_src: yes
        register: unpacked_dir

      - name: 'Compile ruby'
        shell: 'cd {{ tempdir.path }}/ruby-{{ ruby_version.stdout }}/ext/readline; ruby ./extconf.rb; make'

      - name: 'Backup current readline.so'
        copy:
          src: '/usr/lib/x86_64-linux-gnu/ruby/{{ ruby_version.stdout | regex_search("^[0-9]+\.[0-9]+") }}.0/readline.so'
          dest: '/usr/lib/x86_64-linux-gnu/ruby/{{ ruby_version.stdout | regex_search("^[0-9]+\.[0-9]+") }}.0/readline.so.bak'
        become: true

      - name: 'Overwrite with new readline.so'
        copy:
          src: '{{ tempdir.path }}/ruby-{{ ruby_version.stdout }}/ext/readline/readline.so'
          dest: '/usr/lib/x86_64-linux-gnu/ruby/{{ ruby_version.stdout | regex_search("^[0-9]+\.[0-9]+") }}.0/readline.so'
        become: true

      