- name: Alacritty | Configure
  block:
    - name: Alacritty | Configure | Default Terminal
      copy:
        src: files/helpers.rc
        dest: '{{ ansible_env.HOME }}/.config/xfce4/'
    
    - name: Alacritty | Configure | Copy Config File
      copy:
        src: files/alacritty.yml
        dest: '{{ ansible_env.HOME }}/.config/alacritty/'