- name: Alacritty | Install Packages
  ansible.builtin.apt:
    name: alacritty
    state: present
  become: true
    
- name: Alacritty | Configure
  block:
    - name: Alacritty | Configure | Default Terminal
      copy:
        src: files/helpers.rc
        dest: '{{ ansible_env.HOME }}/.config/xfce4/'
    
    - name: Alacritty | Configure | Copy Config File
      copy:
        src: files/alacritty.yml
        dest: '{{ ansible_env.HOME }}/.config/alacritty/'