- name: Apt | Update Cache
  ansible.builtin.apt: 
    update_cache: yes

- name: Apt | Install Packages
  ansible.builtin.apt:
    name: '{{ apt_packages }}'
    state: present
  when: apt_packages | length > 0

