    - name: 'Configure user autologin'
      replace:
        path: /etc/lightdm/lightdm.conf
        regexp: '^#{{ item.key }}=.*$'
        replace: '{{ item.key }}={{ item.value }}'
      with_dict: '{{ lightdm_entries }}'