- name: Boot | Grub
  block:
    - name: Boot | Grub | Set Timeout
      ansible.builtin.lineinfile:
        path: /etc/default/grub
        regexp: '^GRUB_TIMEOUT=.*'
        line: 'GRUB_TIMEOUT=1'
      register: taskresults

    - name: Boot | Grub | Update Grub
      command: update-grub
      when: "taskresults is not skipped"

# do not autologin user on hyper-v as it messes up the enhanced session
- name: Boot | Autologin | Configure Autologin
  replace:
    path: /etc/lightdm/lightdm.conf
    regexp: '^#{{ item.key }}=.*$'
    replace: '{{ item.key }}={{ item.value }}'
  with_dict: '{{ lightdm_entries }}'
  when: ansible_facts.virtualization_type != 'VirtualPC'