- name: Burpsuite | Set Facts
  ansible.builtin.set_fact:
    burpsuite_edition: pro
    burpsuite_channel: Stable
    burpsuite_folder: /opt/burpsuite

- name: Burpsuite | Create Directory
  ansible.builtin.file:
    path: "{{ burpsuite_folder }}"
    state: directory

- name: Burpsuite | Fetch Download URL
  block:
  - name: Burpsuite | Fetch Download URL | Install Pip Packages
    ansible.builtin.pip:
      name: jmespath
    
  - name: Burpsuite | Fetch Download URL | Lookup Latest Version
    block:
    - name: Burpsuite | Fetch Download URL | Lookup Latest Version | Retrieve PortSwigger Releases API Data
      ansible.builtin.set_fact:
        burp_release_data: "{{ lookup('url', 'https://portswigger.net/burp/releases/data?lastId=-1&pageSize=20') }}"

  - name: Burpsuite | Fetch Download URL | Lookup Latest Version | Get Latest Release
    ansible.builtin.set_fact:
      burp_latest_release: "{{ burp_release_data | community.general.json_query(latest_release_query) }}"
    vars:
      latest_release_query: >-
        ResultSet.Results[?contains(@.releaseChannels, '{{ burpsuite_channel }}')].builds[]
        | [?ProductId == '{{ burpsuite_edition }}' && ProductPlatform == 'Linux']
        | [0]

  - name: Burpsuite | Fetch Download URL | Lookup Latest Version | Set Release Facts
    ansible.builtin.set_fact:
      _burpsuite_installer_version: "{{ burp_latest_release | community.general.json_query('@.Version') }}"
      burpsuite_installer_sha256_checksum: "{{ burp_latest_release | community.general.json_query('@.Sha256Checksum') }}"

- name: Burpsuite | Download
  block:
  - name: Burpsuite | Download | Set Jar Filename
    ansible.builtin.set_fact:
      burpsuite_jar: "burpsuite_{{ burpsuite_edition }}_linux_v{{ _burpsuite_installer_version | regex_replace('\\.', '_') }}.jar"

  - name: Burpsuite | Download | Download Jar
    ansible.builtin.get_url:
      url: "https://portswigger.net/burp/releases/download?product={{ burpsuite_edition }}&type=linux&version={{ _burpsuite_installer_version }}"
      dest: "{{ burpsuite_folder }}/{{ burpsuite_jar}}"
      mode: 0644
  

- name: Burpsuite | Extras
  block:
  - name: 'Burpsuite | Extras | Download'
    ansible.builtin.get_url:
      url: "{{ item.value.url }}"
      dest: "{{ burpsuite_folder }}/{{ item.value.jar }}"
      mode: 0644
    loop: "{{ lookup('dict', burpsuite_extras_jars) }}"