---
# tasks file for tools
- name: Tools | Repos
  block:
    - name: Tools | Repos | Create Directory
      file:
        path: "{{ repos_dir }}"
        state: directory
        mode: 0755
        owner: "{{ ansible_env.USER }}"
        group: "{{ ansible_env.USER }}"
      become: true
    
    - name: Tools | Import Tasks | Repos
      include_tasks: repos.yml
  when: repos | length > 0

- name: Tools | Burpsuite
  block:
    - name: Tools | Burpsuite | Create Directory
      ansible.builtin.file:
        path: "{{ burpsuite_folder }}"
        state: directory
        mode: 0755
        owner: "{{ ansible_env.USER  }}"
        group: "{{ ansible_env.USER }}"
      become: true
    
    - name: Tools | Import Tasks | Burpsuite
      include_tasks: burpsuite.yml
  when: burpsuite

- name: Tools | Import Tasks | Evil-WinRM
  include_tasks: ruby.yml
  args:
    apply:
      become: yes
