- name: Releases | {{ item }}
  block:
    - name: Releases | {{ item }} | Fetch Latest Release
      uri:
        url: "https://api.github.com/repos/{{ item }}/releases/latest"
        return_content: true
      register: json_reponse

    - pause:
        prompt: |-
          Select files to download (1,2,...) or press enter to skip:
          ==========================
          {% for file in json_reponse.json.assets %}
          {{ loop.index }}: {{ file.name }}
          {% endfor %}
      register: out

    - set_fact:
        index_list: "{{ out.user_input.split(',')|difference([''])|map('int')|list|sort }}"

    - name: Releases | {{ item }} | Download
      get_url:
        url: "{{ json_reponse.json.assets[selection| int -1].browser_download_url }}"
        dest: "{{ releases_dir }}/{{ json_reponse.json.assets[selection| int -1].name }}"
        mode: 0755
      loop: "{{ index_list }}"
      loop_control:
        loop_var: selection
      when: index_list|length > 0
      ignore_errors: true

    - name: Releases | {{ item }} | Extract And Delete Download
      ansible.builtin.script: "files/extract.py {{ releases_dir }}/{{ json_reponse.json.assets[selection| int -1].name }} {{ releases_dir }}"
      args:
        executable: "/usr/bin/python3"
      loop: "{{ index_list }}"
      loop_control:
        loop_var: selection
      ignore_errors: true

  rescue:
    - debug:
        msg: "Failed to download {{ item }}"
